### ISSUE TITLE
Feature request: filter by technology

### ISSUE THREAD

**Issue by tdamsma** [stfurkan/gez#4]
Great site, much better than googling virtual tours. I would love to be able to filter on the technological implementation (streetview, matter most, just a gallery etc) as especially for kids all the different uis can be confusing

**Comment by stfurkan** [comment]
Hello @tdamsma,

Thank you for your comment and feature request. 

I have a plan to add some new filter options (e.g. hide visited places). I will also consider your request. Most of the virtual tour sites have similar sources like Google Streetview or Matterport. Maybe a filter for virtual tour source can be applied. The problem is some places have its special ui and this might make that filter a little complex.

I will try to find a feasible solution for this.
